# -*- coding: utf-8 -*-
"""Lab2Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDEEYV6QBjMV3m451kZETdJYFNDjB2d-

Matpolib

Numpy

List
"""

num=[1,2,3,4,5,6,7,8,9,10]
print(num)

num=[1,2,3,4,5,6,7,8,9,10]
print("Sum: ",sum(num))

num=[1,2,3,4,5,6,7,8,9,10]
print("Min: ",min(num))
print("Max: ",max(num))

num=[1,2,3,4,5,6,7,8,9,10]
num.append(11)
print("Updated List",num)

num=[1,2,3,4,5,6,7,8,9,10]
print("Ascending: ",sorted(num))
print("Descending: ",sorted(num,reverse=True))

"""Tuple"""

fruits=("mango","orange","strawberry","cherry","pineapple")
print(fruits)

fruits=("mango","orange","strawberry","cherry","pineapple")
print("1st element: ",fruits[0])
print("last element: ",fruits[-1])

fruits=("mango","orange","strawberry","cherry","pineapple")
fruits.append("banana")

fruits=("mango","orange","strawberry","cherry","pineapple")
fruits_list=list(fruits)
fruits_list[2]="banana"

print("Modified List: ",fruits_list)

"""Set"""

set1={1,2,3,4,5,6,7,8,9,10}
set2={11,12,13,14,15,16,17,18,19,20}
print(set1)
print(set2)

set1={1,2,3,4,5,6,7,8,9,10}
set2={10,11,12,13,14,15,16,17,18,19,20}
print("Union: ",set1.union(set2))
print("Intersection: ",set1.intersection(set2))
print("Difference: ",set1.difference(set2))

set1={1,2,3,4,5}
set2={4,5,6,7,8}
set1.add(6)
set2.remove(7)
print("Updated Set1: ",set1)
print("Updated Set2: ",set2)

"""Dictionary

"""

student_marks={
    "gullu":29,
    "Mary":28,
    "Fati":30,
    "Esho":27,
    "Ami":28
    }
print(student_marks)

student_marks={
    "gullu":29,
    "Mary":28,
    "Fati":30,
    "Esho":27,
    "Ami":28
    }
student_marks['Mary']=30
print(student_marks)

student_marks={
    "Mary":29,
    "Mary":28,
    "Mary":30,
    "Mary":27,
    "Mary":28
    }
print(student_marks)